### ISSUE TITLE
Pauses

### ISSUE THREAD

**Issue by domnkysgomoo** [ShadowProgr/DFFOO-Macro#1]
First, thanks a lot for this, it saves a lot of time.

I am having 1 issue and have 1 question.

The issue is the macro randomly "misses" a click I think.  It's happened after 30 runs or after 100 runs, but whenever it comes time to click on the "Auto" button sometimes it doesn't click it.  The mouse moves to Auto but doesn't click and then the progress changes to "waiting for battle to end"  How can I fix this?

The question is, after the battle ends, there is a 20 second lag time on the map where it still says "receiving rewards"  Is there a way to shorten this time to jump directly to select mission quicker?

Thank you

**Comment by BASgamer** [comment]
I edited the click time from 25 to 50. Seemed to help the missed clicks but doesnt work all the time. It doesnt miss clicks on just auto but all of them, but at least on every other step it goes back if it cant find the next step and tries again. 

On the issue with the battle end i think its there to keep trying to keep click in case of level ups and rank ups.

I couldnt figure out how to put a timeout timer to try to detect auto again(if its still auto and not the stop auto button) but some kind of backup would be nice to add so it has a chance to fix itself if it moves to the picture and doesnt successfully click it like it other steps.

**Comment by ShadowProgr** [comment]
Hey there,

About the "missing" clicks, I'm currently still investigating as it seems to vary from PC to PC, some don't run into this issue while some run into it a lot. Increasing the click time helps but it doesn't solve the problem entirely. I'll update that part as soon as I can.

The current solution the script uses is it tries to go back and click the button again if it missed. In case of the Auto button it's supposed to go back to check after reaching the *BattleTimeMax* time.
But as @BASgamer said it's currently bugged and never stops waiting for battle to stop. I'll fix that ASAP

Regarding the battle end, it should only wait up to 5 seconds (based on your *RetryTime* value). I have still yet to find a way to make this quicker, since it needs to check for all possible rewards before continuing

Thanks for reporting the issues, I'll try to fix them next update

**Comment by BASgamer** [comment]
maybe a small delay between moving and clicking would help to make sure the mouse movement isnt lagging behind a little?

**Comment by ShadowProgr** [comment]
It's not the issue of the mouse movement lagging behind, the click isn't executed until the mouse gets into position. It seems that BlueStacks don't register clicks that are too fast, so I have to add a small delay to make a click last longer. I just don't know how much is long enough. And that "enough" seems to vary on different systems

Anyway I fixed the issue of the script not going back to click Auto again in the latest commit. Since it's the original issue, I'm going to close this
